import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gin + NextJS template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden h-screen`}
      >
        <nav className="flex justify-between flex-row w-full items-center border-b-[0.5px] border-gray-700 px-4 py-2">
          <Link href="/">
            Gin + NextJS Template
          </Link>
          <div className="flex w-[150px] justify-between">
            <button className="flex border-[0.5px] py-[5px] px-[10px] bg-white border-white text-black rounded-md">
              <Link href="/register">
                Register
              </Link>
            </button>
            <button className="flex border-[0.5px] py-[5px] px-[10px] border-gray-900 rounded-md">
              <Link href="/login">
                Login
              </Link>
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
